### ISSUE TITLE
Glitch when indexing 32mb PDF file.

### ISSUE THREAD

**Issue by noobAIcoder** [ushakrishnan/SearchWithOpenAI#3] opened 2023-05-25 19:37 UTC
Runs into the same error each time.

```
, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 13}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 929}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 929}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 0}]}
Error loading sou\state_of_the_union.txt
Using embedded DuckDB with persistence: data will be stored in: db/
2023-05-25 21:41:38.534 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 20, in <module>
    st.write(start_capture())
             ^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 12, in start_capture
    store2 = addtostoretxt(folder_name="sou",collection_name="sou_coll",persist_directory="db/")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\common\funs.py", line 47, in addtostoretxt
    store = Chroma.from_documents(docs, embedding=embeddings, collection_name=collection_name, persist_directory=persist_directory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 422, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 390, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 160, in add_texts
    self._collection.add(
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 101, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 348, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\types.py", line 77, in maybe_cast_one_to_many
    if isinstance(target[0], (int, float)):
                  ~~~~~~^^^
IndexError: list index out of range
```

`🦜🔗🤗 Documents Persisted in Vector Database

{
"ids":
[0 - 100]
[100 - 200]
[200 - 300]
[300 - 400]
[400 - 500]
[500 - 600]
[600 - 700]
[700 - 800]
[800 - 900]
[900 - 1000]
[1000 - 1100]
[1100 - 1200]
[1200 - 1300]
[1300 - 1400]
[1400 - 1500]
[1500 - 1600]
[1600 - 1700]
[1700 - 1800]
[1800 - 1900]
[1900 - 2000]
[2000 - 2100]
[2100 - 2200]
[2200 - 2300]
[2300 - 2400]
[2400 - 2500]
[2500 - 2600]
[2600 - 2700]
[2700 - 2800]
[2800 - 2900]
[2900 - 3000]
[3000 - 3030]
"embeddings":NULL
"documents":
[0 - 100]
[100 - 200]
[200 - 300]
[300 - 400]
[400 - 500]
[500 - 600]
[600 - 700]
[700 - 800]
[800 - 900]
[900 - 1000]
[1000 - 1100]
[1100 - 1200]
[1200 - 1300]
[1300 - 1400]
[1400 - 1500]
[1500 - 1600]
[1600 - 1700]
[1700 - 1800]
[1800 - 1900]
[1900 - 2000]
[2000 - 2100]
[2100 - 2200]
[2200 - 2300]
[2300 - 2400]
[2400 - 2500]
[2500 - 2600]
[2600 - 2700]
[2700 - 2800]
[2800 - 2900]
[2900 - 3000]
[3000 - 3030]
"metadatas":
[0 - 100]
[100 - 200]
[200 - 300]
[300 - 400]
[400 - 500]
[500 - 600]
[600 - 700]
[700 - 800]
[800 - 900]
[900 - 1000]
[1000 - 1100]
[1100 - 1200]
[1200 - 1300]
[1300 - 1400]
[1400 - 1500]
[1500 - 1600]
[1600 - 1700]
[1700 - 1800]
[1800 - 1900]
[1900 - 2000]
[2000 - 2100]
[2100 - 2200]
[2200 - 2300]
[2300 - 2400]
[2400 - 2500]
[2500 - 2600]
[2600 - 2700]
[2700 - 2800]
[2800 - 2900]
[2900 - 3000]
[3000 - 3030]
}`

`🦜🔗🤗 What would you like to know?
This sample uses OpenAI

Input your prompt here:

how wood cribs are fastened?
st.warningmethodstreamlit.delta_generator.AlertMixin.warning(body: 'SupportsStr', *, icon: Optional[str] = None) -> 'DeltaGenerator'
Display warning message.

Parameters
----------
body : str
    The warning text to display.
icon : str or None
    An optional, keyword-only argument that specifies an emoji to use as
    the icon for the alert. Shortcodes are not allowed, please use a
    single character instead. E.g. "🚨", "🔥", "🤖", etc.
    Defaults to None, which means no icon is displayed.

Example
-------
>>> import streamlit as st
>>>
>>> st.warning('This is a warning', icon="⚠️")
That was a difficult question! I could choked on it!! Can you please try again with rephrasing it a bit?

Tokens Used: 0 Prompt Tokens: 0 Completion Tokens: 0 Successful Requests: 0 Total Cost (USD): $0.0

This information was found in:

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 19; Similarity Score: 1.1384421586990356

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 78; Similarity Score: 1.2267382144927979

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 72; Similarity Score: 1.2306313514709473

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 609; Similarity Score: 1.246192216873169

38to102mmthick. Direct bearing area —thearea ofoutside lamination over which thepost-tensioning isassumed tobe applied. Direct bearing pressure —theaverage pressure that isassumed tobeapplied tothedirect bearing area bythepost-tensioning force. Distribution bulkhead —asteelsection used todistribute thepost-tensioning force. Drift pin—asteelpinused toconnect wood member s. Duration ofload —aperiod ofcontinuous application ofaspecified load orthesummation ofthetime periods ofinter mittentapplications ofthesame load. External post-tensioning system—asystemthat transv erselypost-tensions alongitudinally laminated wood deck using twobars ateach anchorage, oneabove andonebelow thedeck. Framed bent —alineofwood columns suitably braced. Glued-laminat edtimber (Glulam) —structural wood that ismanufactured inaccordance with CAN/CSA-O122 andisprod uced bygluing together anumber oflaminates with essentially parallel grains. Grade —thedesignation ofthequality ofawood element.`

**Comment by ushakrishnan** [comment] 2023-05-25 22:56
Hello @noobAIcoder, thank you for posting the details.   It looks like the document was indexed (because I am seeing snippets of relevant data) and the failure is while consolidating response through OAI.
Let's try a few things -
- Do you get the error if you clean up the vector database / Chroma and index again before you run the search?
- Is the document a public domain document?  If yes, please send me the link to access it.
- If not public domain, do you have other larger documents where similar issues happen (suggest cleaning Chroma before this test).

**Comment by noobAIcoder** [comment] 2023-05-26 01:40
>Do you get the error if you clean up the vector database / Chroma and index again before you run the search?
Yes.

>Is the document a public domain document? If yes, please send me the link to access it.
Unfortunately it is not.

>If not public domain, do you have other larger documents where similar issues happen (suggest cleaning Chroma before this test).

I've tried doing the same with text version of the file, 2.5 mb.
What are these DPCD-*.pdf? They aren't mentioned anywhere in the document.
Could it be that the database isn't deleted properly?

PD-202200127.pdf', 'page': 11}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 11}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 11}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 12}, {'source': 'sou\\DCPD-202200127.pdf', 'page': 13}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 929}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 929}, {'source': 'sou\\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf', 'page': 0}]}
Error loading sou\Canadian Highway Bridge Design Code.txt
Error loading sou\state_of_the_union.txt
Using embedded DuckDB with persistence: data will be stored in: db/
2023-05-26 04:30:36.534 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 20, in <module>
    st.write(start_capture())
             ^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 12, in start_capture
    store2 = addtostoretxt(folder_name="sou",collection_name="sou_coll",persist_directory="db/")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\common\funs.py", line 47, in addtostoretxt
    store = Chroma.from_documents(docs, embedding=embeddings, collection_name=collection_name, persist_directory=persist_directory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 422, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 390, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 160, in add_texts
    self._collection.add(
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 101, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 348, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\types.py", line 77, in maybe_cast_one_to_many
    if isinstance(target[0], (int, float)):
                  ~~~~~~^^^
IndexError: list index out of range

**Comment by ushakrishnan** [comment] 2023-05-26 10:56
Hello @noobAIcoder, 

thanks for the note of residual files.  In your folder structure you will see a folder called **db**.  Can you check if some *.parquet files or other files have been left over there?  If so, can you share the names of the parquet files, and delete the file on OS.  I run on mac and these are os commands, and have not tested on Windows / Linux.  I will check that this weekend.  

Meanwhile, deleting all files and folders under db folder will clear your Chroma database.

Regarding your other question on DCPD-* files - these are copies of state of the union public files.  I used them for sample documents to be able to run the sample out of the box.  Feel free to delete them and use your own files.  Any file you place in "sou" folder will be indexed when you run the index pdf and txt files page.

**Comment by noobAIcoder** [comment] 2023-05-26 22:30
After cleaning up everything and using only 2.4 mb text file I have this error

`PS C:\Work\Repos\SearchWithOpenAI> streamlit run Home.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.186.60:8501

Could not import azure.core python package.
Using embedded DuckDB without persistence: data will be transient
Has the collection been already deleted?
Have the files been cleanedup already?
True
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
2023-05-27 01:28:31.164 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 20, in <module>
    st.write(start_capture())
             ^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\pages\3_Index_PDFnTXT_Into_ChromaDB_Store.py", line 9, in start_capture
    store2 = addtostorepdf(folder_name="sou",collection_name="sou_coll",persist_directory="db/")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\Repos\SearchWithOpenAI\common\funs.py", line 37, in addtostorepdf
    store = Chroma.from_documents(docs, embedding=embeddings, collection_name=collection_name, persist_directory=persist_directory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 422, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 390, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\vectorstores\chroma.py", line 160, in add_texts
    self._collection.add(
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 101, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\models\Collection.py", line 348, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\types.py", line 77, in maybe_cast_one_to_many
    if isinstance(target[0], (int, float)):
                  ~~~~~~^^^
IndexError: list index out of range`

**Comment by ushakrishnan** [comment] 2023-05-26 23:03
@noobAIcoder I just posted a fix to this issue.  When either pdf files do not exist in db folder or no txt files in folder, this error comes up.  The fix is in two files - \common\funs.py and 3_Index_PDFnTXT_Into_ChromaDB_Store.py.  Alternatively,  you can download the git again.
fix posted: https://github.com/ushakrishnan/SearchWithOpenAI/commit/2d0d7f7211db1d2ed58f9c74d4befe87689b7a2d

**Comment by noobAIcoder** [comment] 2023-05-27 00:53
Now it ignores text file but indexes pdf file.
However, after indexing the search does't yield proper results

This is the phrase that I'm searching for: The ratio of length to diameter of any cylindrical roller or roller segment shall not exceed 3.25.
It is found on page 927
However, these results are a bit off.
Simpler prompts yield similar results.

`🦜🔗🤗 What would you like to know?
This sample uses OpenAI

Input your prompt here:

tell me about The ratio of length to diameter of any cylindrical roller or roller segment
st.warningmethodstreamlit.delta_generator.AlertMixin.warning(body: 'SupportsStr', *, icon: Optional[str] = None) -> 'DeltaGenerator'
Display warning message.

Parameters
----------
body : str
    The warning text to display.
icon : str or None
    An optional, keyword-only argument that specifies an emoji to use as
    the icon for the alert. Shortcodes are not allowed, please use a
    single character instead. E.g. "🚨", "🔥", "🤖", etc.
    Defaults to None, which means no icon is displayed.

Example
-------
>>> import streamlit as st
>>>
>>> st.warning('This is a warning', icon="⚠️")
That was a difficult question! I could choked on it!! Can you please try again with rephrasing it a bit?

Tokens Used: 0 Prompt Tokens: 0 Completion Tokens: 0 Successful Requests: 0 Total Cost (USD): $0.0

This information was found in:

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 720; Similarity Score: 1.22101628780365

or 0.1times themean radius ofthegirder . c) Flanges shall beClass 3orbetter. 10.13.6.1.2 Flanges Flanges shall beproportioned tosatisfy thefollowing requirements: a) Strength ofeither flange: where MrxI=IϕsFySx MfwI=Ifactored bending moment intheflange duetotorsional warping. Mfwmay becalculated in accordance with Annex A5.1. Alternatively ,Mfwmay beobtained directly froma geometrically non-linear model using linear elastic materia lproper ties. MryI=IϕsFySyf

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 670; Similarity Score: 1.3048021793365479

onthecomposit esection (ifapplicable) (see Clause 10.7.4.3), mm ΔmI =Imaximum value ofΔDL+ΔSDLwithin length L(see Clause 10.7.4.3), mm ΔrI =Iadditional camber forhorizontally heat-curved beams (see Clause 10.7.4.3), mm θI =Iangle between theaxisoftheweld segment andthelineofaction oftheapplied force (e.g., 0°foralongitudinal weld and90°foratransver seweld) (see Clause 10.18.3.2.2); angle ofinclination ofweb plateofboxgirders tothevertical, degrees; angle ofweld axisto lineofaction offorce, degrees κI =Iratio ofthesmaller factored moment tothelarger factored moment atopposite ends ofan unbraced length (positive fordouble curvature andnegative forsingle curvature) λI =Inon-dimensional slenderness parameter incolumn formula; slenderness paramet er λcI =Islenderness paramet erforconcret eportion ofcomposit ecolumn λeI =Iequivalent slenderness paramet er ρI =Ifactor modifying contribution ofsteeltocompressive resistance ofcomposit ecolumn τ,τ′I =Ifactor smodifying contributions

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 662; Similarity Score: 1.324774980545044

distance fromfree edge ofplates tothefirstlineofbolts orwelds; width ofstiffener; width ofbottom flange platebetween webs ofboxgirder ,mm b′I =Iflatwidth ofonesideofamulti-sided hollow section, mm bcI =Iwidth ofconcret eattheneutral axis, mm(see Clause 10.9.5.5) beI =Ieffective width ofconcret eslab, mm bfI =Iwidth ofwidest flange ofcurved welded I-girders, mm bsI =Iwidth ofcompression flange between longitudinal stiffeners ,mm; distance from web to neares tlongitudinal stiffener ,mm CI =Icoefficient informula forarea ofstiffener; coefficient informula formoment resistance of unstiffened compression flanges ofcomposit eboxgirders CBI =Ibracing coefficient forcantilever beams CHI =Iload height coefficient forcantilever beams CLI =Icorrection factor forfatigue truck weight CcI =Ifactored compressive resistance ofconcrete, N CeI =IEuler buckling load, N CecI =IEuler buckling load ofaconcrete-fi lledhollow structural section, N

Source: sou\CSA - S6-19_EN_Canadian Highway Bridge Design Code.pdf - Page: 1096; Similarity Score: 1.3319196701049805

thestrongaxis, mm3 SyI =Isection modulus ofthegrosssection about theweak axis, mm3 sI =Ispacing offastener salong alineofconnections; distance between transv erse stiffeners; centre-to-centre distance between adjacent bolts onthecircle ofaboltgroup (see Clause 17.22.2.8); spacing ofsuccessive holes inthedirection oftheforce, mm TI =Itension inbolts atSLS,N TaI =Ifactored tensileresistance ofaluminum section orcomponent, N TfI =Ifactored tensileforce inamember ,bolt, orcomponent atULS, N TrI =Ifactored tensileresistance ofamember ,bolt, orcomponent, N tI =Ielement thickness; original thickness; flange thickness; thethickness ofthewider legof thecomponent angles; wall thickness ofthepipe ortube; minimum thickness (see Clause 17.13.2.1); thickness ofindividual wall (see Clause 17.13.4.1); platethickness (see Clause 17.22.2.6.1); thickness ofthinner outside plateorshape (see Clause 17.22.2.10.6), mm tbI =Ithickness ofbottom flange, mm --,,```````,``,,`````,--,,,,,,,`---`

**Comment by ushakrishnan** [comment] 2023-05-27 02:48
@noobAIcoder The fix will not throw an error is any file type is absent but will index all files in the folder.  I am not sure of the content of the file or search.  I could try it myself if this is a public domain file.  If it is not a file in public domain, then I. suggest you try with textual based files first to make sure the tools works as intended. 

Also, looks like there is an error.  Can you grab the exception details from the command prompt for the error?

**Comment by noobAIcoder** [comment] 2023-05-27 09:59
Text files are not processed due to some error.
PDF files are indexed and search is kinda working, but it won't retrieve correct page numbers.

> Entering new AgentExecutor chain...
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB with persistence: data will be stored in: db/
Using embedded DuckDB without persistence: data will be transient
Has the collection been already deleted?
True
Number of PDF pages to be indexed: 0
Error loading sou\state_of_the_union.txt
Number of TXT documents to be indexed: 0
Using embedded DuckDB with persistence: data will be stored in: db/
Number of PDF pages to be indexed: 0
Error loading sou\state_of_the_union.txt
Number of TXT documents to be indexed: 0
Using embedded DuckDB with persistence: data will be stored in: db/
Number of PDF pages to be indexed: 0
Error loading sou\Canadian Highway Bridge Design Code.txt
Error loading sou\state_of_the_union.txt
Number of TXT documents to be indexed: 0
Using embedded DuckDB with persistence: data will be stored in: db/
Number of PDF pages to be indexed: 14
Using embedded DuckDB with persistence: data will be stored in: db/
Error loading sou\Canadian Highway Bridge Design Code.txt
Error loading sou\state_of_the_union.txt
Number of TXT documents to be indexed: 0
Using embedded DuckDB with persistence: data will be stored in: db/

**Comment by ushakrishnan** [comment] 2023-05-28 23:51
@noobAIcoder  
1. For TXT file processing error
- Can you check the file permissions? Easier - Can you delete that txt file and download the txt again and try?  
2. For not getting the best search results
- without being able to look at the pdf you are searching, I am unable to find the reason.  Does the file contain a lot of scientific text and / diagrams?  Possibilities to test - 
- Can you try searching with different pdf and see if the response is better?
- I am planning to incorporate other types of searches (FAISS) and other models to see if that improves scores.  I will let you. know when those options are ready for your test again.

**Closed as completed** 2023-06-03 22:58 UTC

**Comment by ushakrishnan** [comment] 2023-06-12 15:32
@noobAIcoder 

For txt file processing error on windows:  I realize that this is due to encoding of the txt file.  the state of union.txt file was UTF-8 encoded.  I changed that to ANSI and saved it and it worked.  While I will make changes to accommodate the difference, for now, please use ANSI encoding txt files for testing.
